version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:15.3-alpine3.18
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  backend:
    image: qjgns/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db
    restart: always

  frontend:
    env_file: .env
    image: qjgns/kittygram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  gateway:
    image: qjgns/kittygram_gateway
    env_file: .env
    ports:
      - "9000:80"
    volumes:
      - static:/static
      - media:/mediafiles
    depends_on:
      - backend
    restart: always
